from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Iterable

from .models import ResolvedPeer
from .paths import SuitePaths


def _quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def managed_toml_path(config: Dict[str, Any], paths: SuitePaths) -> Path:
    existing = config.get("upstream", {}).get("existing_config")
    if existing:
        source = Path(existing).expanduser()
        return source.with_name("config.lanmouse-suite.toml")
    return paths.generated_toml


def render_toml(config: Dict[str, Any], peers: Iterable[ResolvedPeer]) -> str:
    upstream = config["upstream"]
    lines = [
        "# Generated by Lan Mouse Suite. Edit config.json, not this file.",
        "port = %d" % upstream.get("port", 4242),
        "release_bind = [" + ", ".join(_quote(key) for key in upstream["release_chord"]) + "]",
        "",
        "[authorized_fingerprints]",
    ]
    for fingerprint, label in sorted(upstream.get("authorized_fingerprints", {}).items()):
        lines.append("%s = %s" % (_quote(fingerprint.lower()), _quote(label)))
    lines.append("")
    for peer in peers:
        lines.extend(
            [
                "[[clients]]",
                "hostname = %s" % _quote(peer.address),
                "ips = [%s]" % _quote(peer.address),
                "position = %s" % _quote(peer.position),
                "port = %d" % peer.port,
                "activate_on_startup = true",
                "",
            ]
        )
    return "\n".join(lines)


def write_managed_toml(config: Dict[str, Any], peers: Iterable[ResolvedPeer], paths: SuitePaths) -> Path:
    target = managed_toml_path(config, paths)
    target.parent.mkdir(parents=True, exist_ok=True)
    new_text = render_toml(config, peers)
    if not target.exists() or target.read_text(encoding="utf-8") != new_text:
        temporary = target.with_name(target.name + ".tmp")
        temporary.write_text(new_text, encoding="utf-8")
        temporary.chmod(0o600)
        temporary.replace(target)
    return target
